import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
} from '@nestjs/common';

export const attendanceErrorCodes = [
  'activeShiftExists',
  'belowMinimumWorkingAge',
  'belowStatutoryPaidPercent',
  'breakTooShort',
  'calendarLeaveInterval',
  'calendarLeavePayRequired',
  'cannotReviewOwnDraft',
  'cannotReviewSelf',
  'childLaborHoursExceeded',
  'childLaborNightWork',
  'childLaborRestDay',
  'continuousWorkTooLong',
  'correctionSourceChanged',
  'dailyHoursExceeded',
  'emergencyDetailsRequired',
  'employeeDisableConflict',
  'employeeNotEnabled',
  'employmentInsuranceExemptionInvalid',
  'employmentInsuranceIneligible',
  'employmentInsuranceRequired',
  'employmentWindowConflict',
  'futureCorrection',
  'healthInsuranceExemptionInvalid',
  'healthInsuranceRequired',
  'holidayCalendarMissing',
  'idempotencyConflict',
  'implausibleMinimumWage',
  'insufficientLeaveBalance',
  'invalidBreak',
  'invalidEmergencyDetails',
  'invalidEventSequence',
  'invalidInterval',
  'invalidIp',
  'invalidLeaveCase',
  'invalidParentalInterval',
  'invalidPayrollState',
  'ipNotAllowed',
  'laborInsuranceExemptionInvalid',
  'laborInsuranceRequired',
  'leaveCaseExists',
  'leaveCaseInUse',
  'leaveCaseIntervalConflict',
  'leaveCaseRequired',
  'leaveOutsideShift',
  'leavePolicyRequired',
  'leavePolicyRulesRequired',
  'leaveTypeInUse',
  'locationNotAllowed',
  'medicalCertificateRequired',
  'medicalLeaveInterval',
  'memberNotFound',
  'menstrualDayLimit',
  'monthlyOvertimeExceeded',
  'noTemplateDates',
  'outsideShiftWindow',
  'overlappingAttendance',
  'overlappingLeave',
  'overlappingOvertimeExtensions',
  'overlappingShift',
  'parentalChildExists',
  'parentalChildMismatch',
  'parentalChildRequired',
  'parentalChildUnassigned',
  'parentalDailyLimit',
  'parentalLeaveActive',
  'parentalReturnInvalid',
  'parentalReturnPending',
  'parentalReturnStale',
  'parentalShortLimit',
  'parentalTotalLimit',
  'partTimeLadderRequiresPartTime',
  'payrollBlocked',
  'payrollLocked',
  'payrollRuleSetMissing',
  'payrollSourceChanged',
  'payrollTermsRequired',
  'pendingRequestExists',
  'pensionIneligible',
  'pensionRequired',
  'periodOvertimeExceeded',
  'reasonRequired',
  'requestAlreadyReviewed',
  'reservedMakeupRest',
  'settingsRequired',
  'shiftHasCorrection',
  'shiftHasRecords',
  'shiftRequired',
  'shiftRestTooShort',
  'shiftTooLong',
  'splitLeaveByYear',
  'statutoryBalanceAutomatic',
  'statutoryLeaveTypeLocked',
  'studentWeeklyHoursExceeded',
  'weeklyRestRequired',
  'workPermitRequired',
] as const;

export type AttendanceErrorCode = (typeof attendanceErrorCodes)[number];

export const badRequestError = (code: AttendanceErrorCode) =>
  new BadRequestException(code);

export const conflictError = (code: AttendanceErrorCode) =>
  new ConflictException(code);

export const forbiddenError = (code: AttendanceErrorCode) =>
  new ForbiddenException(code);
